### ISSUE TITLE
R.utils::evalWithTimeout() -> withTimeout()

### ISSUE THREAD

**Issue by HenrikBengtsson** [nuno-agostinho/psichomics#383]
Hi. The psichomics package calls `evalWithTimeout()` of R.utils.  This function was deprecated in R.utils 2.6.0 (2017-11-05), which meant it was producing a warning everything it was called.  It was then made defunct in R.utils 2.8.0 (2018-08-26), meaning it produced a run-time error.

I'm preparing the release of R.utils 2.9.0 where `evalWithTimeout()` has been removed.  This break your package, i.e. it won't install:

```
* installing *source* package ‘psichomics’ ...
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hb/repositories/R.utils/revdep/library/psichomics/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3U0YWo/r-base-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/hb/repositories/R.utils/revdep/library/psichomics/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3U0YWo/r-base-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c psiFastCalc.cpp -o psiFastCalc.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o psichomics.so RcppExports.o psiFastCalc.o -L/usr/lib/R/lib -lR
installing to /home/hb/repositories/R.utils/revdep/checks/psichomics/new/psichomics.Rcheck/psichomics/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error : object ‘evalWithTimeout’ is not exported by 'namespace:R.utils'
ERROR: lazy loading failed for package ‘psichomics’
* removing ‘/home/hb/repositories/R.utils/revdep/checks/psichomics/new/psichomics.Rcheck/psichomics’
```

Please update code to call `withTimeout()` instead. That's all that is needed. `withTimeout()` has been available since R.utils 2.2.0 (2015-12-09).

It would be particularly useful if you could fix this for the current Bioc version before the upcoming freeze.

Thanks

**Comment by nuno-agostinho** [comment]
Fixed! Thank you for the heads up, @HenrikBengtsson 😄

**Comment by HenrikBengtsson** [comment]
Thanks for the quick fix.

**Comment by HenrikBengtsson** [comment]
Did you push this also to Bioc release?

I see that https://bioconductor.org/packages/3.9/bioc/html/psichomics.html is updated, but not https://bioconductor.org/packages/3.8/bioc/html/psichomics.html.  It could be that it takes more than two days but, if not, please consider fixing that too because people will stay on R 3.5.3 for a while and they'll get that version of your package and with R.utils 2.9.0 on CRAN, it will break for them.

**Comment by nuno-agostinho** [comment]
> Did you push this also to Bioc release?

I tried but the 3.8 branch is already frozen with the [imminent release of the 3.9 branch](https://bioconductor.org/developers/release-schedule/)... I cannot make changes in that version any more.

**Comment by HenrikBengtsson** [comment]
Ah.. that's unfortunate. I missed that announcement:

On Mon, Apr 15, 2019, 05:12 Shepherd, Lori wrote:

Today is the last day to commit any changes to the release 3.8 branch.  The branch will be frozen to commits as of 4:45 PM  EST.
