### ISSUE TITLE
junction quantification data not loading

### ISSUE THREAD

**Issue by MikeHH01** [nuno-agostinho/psichomics#385]
Hi

Psichomics had been working fine on my Mac up to this week - using RStudio with R 3.6 on OS Mojave, and downloaded from Bioconductor. However, today I cannot load the junction quantification data from TCGA. I've tried loading the file I've already used successfully, and also tried downloading the data again, reloading psichomics from Bioconductor, updating the OS, restarting , closing safari and nothing will load. When I select the junction data file to load nothing happens. The gene expression data loads fine.
Any advice for this?

Many thanks

Mike Herbert
mike.hrbrt@gmail.com

**Comment by MikeHH01** [comment]
I've fixed this- file location problem

**Comment by nuno-agostinho** [comment]
Hey @MikeHH01, I am glad you could make it work.

Do you have any suggestion to improve or avoid this issue? Maybe the interface could be somewhat clearer? Thanks in advance!

**Comment by PedroBarbosa** [comment]
Hi,

I'm also having the same issue, in this case loading local junction data.
It finds both 'psichomics_gene_counts' and 'psichomics_junctions.txt' files, but I get a list with just 1 element, referring to gene expression data. Please find attached the first 10 lines of each file.

`data <- loadLocalFiles("~/Downloads//star_counts/psichomics")`

[psichomics_gene_counts_head.txt](https://github.com/nuno-agostinho/psichomics/files/3359015/psichomics_gene_counts_head.txt)
[psichomics_junctions_head.txt](https://github.com/nuno-agostinho/psichomics/files/3359016/psichomics_junctions_head.txt)

Any help?
Thanks in advance,
Pedro Barbosa
