### ISSUE TITLE
'parseMatsAnnotation' requires "AFE" and "ALE" txt, which are not produced by rmats

### ISSUE THREAD

**Issue by YingziZhang-github** [nuno-agostinho/psichomics#406]
Dear Nuno,
I want to use alternative splicing annotation form rmats. Referring to [this,](https://bioconductor.org/packages/release/bioc/vignettes/psichomics/inst/doc/AS_events_preparation.html) I used this command:
```
matsOutput <- "path/to/rMATS/output"
mats <- parseMatsAnnotation(matsOutput, genome = "fromGTF",novelEvents=TRUE).
``` 
Then it reported `cannot open file '~/Sequentia-rMATS-1strand/fromGTF.AFE.txt': No such file or directory`
I saw the code and found it need to search for AFE.txt and ALE.txt. However, I think rmats doesn't reproduce these outputs. It can be confirmed both in its outputs and in its [website.](http://rnaseq-mats.sourceforge.net/) Do you have any suggestions on how should I make this?
Thank you.

Best,
Yingzi

**Comment by nuno-agostinho** [comment]
Hey @YingziZhang-github! Earlier versions of rMATS used to create annotation for alternative first and last events (AFE and ALE, respectively). It seems that newer versions do not create those anymore.

Anyway, the `parseMatsAnnotation()` function has an argument called `types` that you can use to indicate which splicing event types to load. In this case, run the following command:

```
mats <- parseMatsAnnotation(matsOutput, types = c("SE", "MXE", "A5SS", "A3SS", "RI"),
                            genome = "fromGTF", novelEvents=TRUE)
```

Please feel free to reply as needed! Thank you :)

**Comment by YingziZhang-github** [comment]
Thank you Nuno. After using the function, it worked smoothly.

Best,
Yingzi
