### ISSUE TITLE
the rownames of PSI generated using the custom annotation doesn't contain gene names

### ISSUE THREAD

**Issue by YingziZhang-github** [nuno-agostinho/psichomics#407]
Hi Nuno,
As the title says, I see the row names of PSI generated using the custom annotation doesn't contain gene names, the same as your [manual](https://bioconductor.org/packages/release/bioc/vignettes/psichomics/inst/doc/AS_events_preparation.html) shows. See this: 
`psi # may have 0 rows because of the small junction quantification set
                                                Normal 1  Normal 2 Normal 3
 SE_1_+_23385660_23385840_23385851_23395032_ 0.7777778 0.4444444      0.6
                                               Cancer 1  Cancer 2  Cancer 3
 SE_1_+_23385660_23385840_23385851_23395032_      0.4 0.4285714 0.5555556`

In another [manual](https://nuno-agostinho.github.io/psichomics/articles/CLI_tutorial.html), there are gene names in PSI row names. See this: 
`events <- rownames(psi)
head(events)
[1] "SE_3_+_13661331_13663275_13663415_13667945_FBLN2"
[2] "SE_3_+_57908750_57911572_57911661_57913023_SLMAP"
[3] "ALE_3_+_57908750_57911572_57913023_SLMAP"
[4] "SE_3_-_37136283_37133029_37132958_37125297_LRRFIP2"
[5] "SE_12_-_56558432_56558152_56558087_56557549_SMARCC2"
[6] "AFE_4_+_56755098_56750094_56756389_EXOC1"`

I want to search AS events for certain genes. And, I see the manual shows how to take advantage of these gene names information also. Do you know what should I do to get gene names when using custom annotation?
Thank you very much.

Best,
Yingzi

**Comment by nuno-agostinho** [comment]
Hello @YingziZhang-github,

Sorry for the delay in answering!

Currently, there is no automatic way to include gene symbols in custom annotations. I will soon update psichomics to account for this.

In the meantime, you could include them manually by following the script here: https://github.com/nuno-agostinho/alternativeSplicingEvents.hg19/blob/050e4920e732ec1ae6e93df317cacc0e75805cab/inst/scripts/make-data.R#L173-L285

I will let you know when the automatic retrieval of gene symbols is available. All the best!

Cheers,
Nuno

**Comment by YingziZhang-github** [comment]
Okay. Thanks!

Best,
Yingzi

**Comment by nuno-agostinho** [comment]
Hello @YingziZhang-github! You can now update to [psichomics 1.14.2](https://github.com/nuno-agostinho/psichomics/releases/tag/1.14.2) and use the exact same commands you were using. psichomics now retrieves the genes from the provided annotations.

Please feel free to contact me if you have any questions. Thanks! :)
