### ISSUE TITLE
Install and start running

### ISSUE THREAD

**Issue by RFTHK** [nuno-agostinho/psichomics#423]
Hi,

I'd like to use your psichomics visual interface, but can not install and start the program because of the following message.
I am using Windows and RStudio version 4.1.0 (2021-05-18). What is the problem?

> library(psichomics)
Loading required package: shiny
Loading required package: shinyBS
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
Error: package or namespace load failed for ‘psichomics’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘org.Hs.eg.db’
> psichomics()
Error in psichomics() : could not find function "psichomics"

Ryo

**Comment by nuno-agostinho** [comment]
Hey Ryo, what version of psichomics do you have installed (you can check with `packageVersion("psichomics")`)? Please try to update to the latest version.

You can also try to manually install org.Hs.eg.db via `BiocManager::install("org.Hs.eg.db")`, although this package is no longer a dependency in the newest version of psichomics.

**Comment by RFTHK** [comment]
Thank you very much for your quick response. The version is 1.17.0. (installed on 2021/05/21).

`packageVersion("psichomics")`
[1] ‘1.17.0’

Manual installation of `org.Hs.eg.db` could not improve the problem...

Ryo

**Comment by nuno-agostinho** [comment]
Okay, so there is a 1.18.0 version of psichomics. Could you try to update to this version using Bioconductor (`BiocManager::install("psichomics")`)? If that doesn't work, please try to install the latest version directly from GitHub with:

```R
install.packages("remotes"); remotes::install_github("nuno_agostinho/psichomics", ref="master")
```

**Comment by RFTHK** [comment]
I have installed and started psichomics version 1.17.0, although a version 1.18.0 cannot be installed in my Windows environment.
I will proceed my analysis with 1.17.0. Thank you very much for creating such a great program and for your kind help.

Ryo
