### ISSUE TITLE
Visual interface not starting with new R v.4.1.1

### ISSUE THREAD

**Issue by SaraL-GH** [nuno-agostinho/psichomics#432]
Hello,
I have updated my R and RStudio, re-installed all the packages (I had saved the list) but now I am having issues while using psichomics() to open the web interface.
I've got shiny and shinyBS installed, I am not sure if there are any other dependencies that for some reason were not re-installed in my new version of R.
I'm copying the messages I get, it would be amazing to have some help:

> library(psichomics)
Loading required package: shiny
Loading required package: shinyBS
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)

psichomics 1.18.5: start the visual interface by running psichomics()
Full documentation and tutorials at https://nuno-agostinho.github.io/psichomics
> psichomics()
This Font Awesome icon ('envelope-o') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('thumb-tack') is deprecated in Font Awesome 5:
* please consider using 'thumbtack' or 'fas fa-thumbtack' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('thumb-tack') is deprecated in Font Awesome 5:
* please consider using 'thumbtack' or 'fas fa-thumbtack' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('thumb-tack') is deprecated in Font Awesome 5:
* please consider using 'thumbtack' or 'fas fa-thumbtack' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('thumb-tack') is deprecated in Font Awesome 5:
* please consider using 'thumbtack' or 'fas fa-thumbtack' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('sliders') is deprecated in Font Awesome 5:
* please consider using 'sliders-h' or 'fas fa-sliders-h' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('calendar-times-o') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('pencil') is deprecated in Font Awesome 5:
* please consider using 'pencil-alt' or 'fas fa-pencil-alt' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('pencil') is deprecated in Font Awesome 5:
* please consider using 'pencil-alt' or 'fas fa-pencil-alt' instead
* use the `verify_fa = FALSE` to deactivate these messages
The `name` provided ('file-text') is deprecated in Font Awesome 5:
* please consider using 'file-alt' or 'fas fa-file-alt' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('envelope-o') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
Error in nav[[3]][[1]][[3]][[1]][[3]][[2]] : subscript out of bounds 

Thanks in advance!

**Comment by nuno-agostinho** [comment]
Hey @SaraL-GH, the problem is related with using psichomics 1.18.5 (or lower) and shiny 1.7.0.

I already fixed this in [psichomics 1.18.6](https://github.com/nuno-agostinho/psichomics/releases/tag/1.18.6). This version should be available in Bioconductor soon. If you want, you can install the newest version from GitHub via R:
```R
install.packages("remotes"); remotes::install_github("nuno-agostinho/psichomics@1.18.6")
```

Note that if you install psichomics via GitHub, you won't automatically get future updates to psichomics (but you can always install the Bioconductor version afterwards if you want).

If you have further questions, feel free to ask! Best regards :)
