### ISSUE TITLE
Warning: Correlation analyses already performed [in "Correlation analyses"]

### ISSUE THREAD

**Issue by SaraL-GH** [nuno-agostinho/psichomics#436]
Hello, my students are having issues with the 'correlation analysis' function on the web interface (same error for both of them on two different machines, latest versions of R and psichomics installed). Specifically, when they do correlation analyses with a certain splicing event and then move on to another alternative splicing event, they get a pop-up saying "correlation analysis already performed, do you wish to discard the current results?"
![image](https://user-images.githubusercontent.com/62432299/150838402-214804d3-515c-4b6b-a193-4a84dc41c304.png)

and although they select "Discard" they can't move forward. The console also shows "Warning: Correlation analyses already performed [in "Correlation analyses"]".

We tried to go do another analysis with the new event first and then go to Correlation analysis, but it still does not load the new event. Any tips to overcome this? The only thing working so far is to close the web interface and start it again.
Thanks!

**Comment by nuno-agostinho** [comment]
Hey @SaraL-GH, thanks for reporting this issue!

I just released psichomics 1.20.1 to fix this issue. It will be in Bioconductor in a couple of days, but you can download it now from GitHub using:

```
install.packages("remotes")
remotes::install_github("nuno_agostinho/psichomics", ref="1.20.1")
```

If you have any more issues, please feel free to ask.
